Boolean AND

In [9]:
theta = 0
w = 1
sum = 0

In [10]:
a = [[0,0,0],
     [0,1,0],
     [1,0,0],
     [1,1,1]]

In [11]:
def threshold(theta,sum):
    if sum >= theta:
        return 1
    else:
        return 0

In [12]:
for i in range(len(a)):
    sum = 0
    for j in range(len(a[i])-1):
        sum += a[i][j]*w
    print("AND({},{}) = {}".format(a[i][0],a[i][1],threshold(len(a[i])-1,sum)))

AND(0,0) = 0
AND(0,1) = 0
AND(1,0) = 0
AND(1,1) = 1


Boolean OR

In [13]:
theta = 0
w = 1
sum = 0

In [14]:
a = [[0,0,0],
     [0,1,1],
     [1,0,1],
     [1,1,1]]

In [15]:
def threshold(theta,sum):
    if sum >= theta:
        return 1
    else:
        return 0

In [16]:
for i in range(len(a)):
    sum = 0
    for j in range(len(a[i])-1):
        sum += a[i][j]*w
    print("OR({},{}) = {}".format(a[i][0],a[i][1],threshold(1,sum)))

OR(0,0) = 0
OR(0,1) = 1
OR(1,0) = 1
OR(1,1) = 1


Boolean NOR

In [ ]:
theta = 0
w = 1
sum = 0

In [ ]:
a = [[0,0,0],
     [0,1,1],
     [1,0,1],
     [1,1,1]]

In [ ]:
def threshold(theta,sum):
    if sum == theta:
        return 1
    else:
        return 0

In [ ]:
for i in range(len(a)):
    sum = 0
    for j in range(len(a[i])-1):
        sum += a[i][j]*w
    print("NOR({},{}) = {}".format(a[i][0],a[i][1],threshold(0,sum)))

NOR(0,0) = 1
NOR(0,1) = 0
NOR(1,0) = 0
NOR(1,1) = 0


Boolean NOT

In [ ]:
theta = 0
w = 1
sum = 0

In [ ]:
a = [[0,0],
     [1,0]]

In [ ]:
def threshold(theta,sum):
    if sum == theta:
        return 1
    else:
        return 0

In [ ]:
for i in range(len(a)):
    sum = 0
    for j in range(len(a[i])-1):
        sum += a[i][j]*w
    print("NOR({},{}) = {}".format(a[i][0],a[i][1],threshold(0,sum)))

NOR(0,0) = 1
NOR(1,0) = 0


# Perceptron

In [17]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import pandas as pd
data = pd.read_csv('diabetes.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
a = data.iloc[:,:8]
input_ = a.values.tolist()
input_

[[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0],
 [1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0],
 [8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0],
 [1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0],
 [0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0],
 [5.0, 116.0, 74.0, 0.0, 0.0, 25.6, 0.201, 30.0],
 [3.0, 78.0, 50.0, 32.0, 88.0, 31.0, 0.248, 26.0],
 [10.0, 115.0, 0.0, 0.0, 0.0, 35.3, 0.134, 29.0],
 [2.0, 197.0, 70.0, 45.0, 543.0, 30.5, 0.158, 53.0],
 [8.0, 125.0, 96.0, 0.0, 0.0, 0.0, 0.232, 54.0],
 [4.0, 110.0, 92.0, 0.0, 0.0, 37.6, 0.191, 30.0],
 [10.0, 168.0, 74.0, 0.0, 0.0, 38.0, 0.537, 34.0],
 [10.0, 139.0, 80.0, 0.0, 0.0, 27.1, 1.441, 57.0],
 [1.0, 189.0, 60.0, 23.0, 846.0, 30.1, 0.398, 59.0],
 [5.0, 166.0, 72.0, 19.0, 175.0, 25.8, 0.587, 51.0],
 [7.0, 100.0, 0.0, 0.0, 0.0, 30.0, 0.484, 32.0],
 [0.0, 118.0, 84.0, 47.0, 230.0, 45.8, 0.551, 31.0],
 [7.0, 107.0, 74.0, 0.0, 0.0, 29.6, 0.254, 31.0],
 [1.0, 103.0, 30.0, 38.0, 83.0, 43.3, 0.183, 33.0],
 [1.0, 115.0, 70.0, 30.0, 96.0

In [ ]:
output = data['Outcome'].tolist()
output

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,


In [ ]:
import numpy as np
w = np.zeros((768,9))
w

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
import random

In [ ]:
for i in range(768):
    for j in range(9):
        a = round(random.uniform(0, 1), 2)
        w[i][j] = a
w

array([[0.48, 0.19, 0.69, ..., 0.48, 0.2 , 0.57],
       [0.4 , 0.87, 0.79, ..., 0.12, 0.75, 0.71],
       [0.48, 0.32, 0.61, ..., 0.47, 0.77, 0.13],
       ...,
       [0.24, 0.7 , 0.21, ..., 0.27, 0.38, 0.44],
       [0.91, 0.21, 0.07, ..., 0.76, 0.6 , 0.21],
       [0.41, 0.2 , 0.44, ..., 0.48, 0.41, 0.94]])

In [ ]:
b = round(random.uniform(0, 1), 2)
b

0.54

In [ ]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [ ]:
def error(out,i):
    return output[i] - out

In [ ]:
errors = np.zeros((768,9)).astype(float)
errors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y_pred = []
for i in range(768):
    sum = 0
    out = 0
    a = 0
    for j in range(8):
        sum += input_[i][j]*w[i][j] + b
    out = step_function(sum)
    a = error(out,i)
    if a != 0:
        errors[i][j] = a
    while a != 0:
        for j in range(8):
            sum += input_[i][j]*w[i][j] + b
        out = step_function(sum)
        a = error(out,i)
        if a != 0:
            errors[i][j] = a 
        for j in range(8):
            w[i][j] = w[i][j] + a*output[i]
        b = b + a
    y_pred.append(out)
    print("Diabetes({}) = {}".format(input_[i],out))

Diabetes([6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0]) = 1
Diabetes([1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0]) = 0
Diabetes([8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0]) = 1
Diabetes([1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0]) = 0
Diabetes([0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0]) = 1
Diabetes([5.0, 116.0, 74.0, 0.0, 0.0, 25.6, 0.201, 30.0]) = 0
Diabetes([3.0, 78.0, 50.0, 32.0, 88.0, 31.0, 0.248, 26.0]) = 1
Diabetes([10.0, 115.0, 0.0, 0.0, 0.0, 35.3, 0.134, 29.0]) = 0
Diabetes([2.0, 197.0, 70.0, 45.0, 543.0, 30.5, 0.158, 53.0]) = 1
Diabetes([8.0, 125.0, 96.0, 0.0, 0.0, 0.0, 0.232, 54.0]) = 1
Diabetes([4.0, 110.0, 92.0, 0.0, 0.0, 37.6, 0.191, 30.0]) = 0
Diabetes([10.0, 168.0, 74.0, 0.0, 0.0, 38.0, 0.537, 34.0]) = 1
Diabetes([10.0, 139.0, 80.0, 0.0, 0.0, 27.1, 1.441, 57.0]) = 0
Diabetes([1.0, 189.0, 60.0, 23.0, 846.0, 30.1, 0.398, 59.0]) = 1
Diabetes([5.0, 166.0, 72.0, 19.0, 175.0, 25.8, 0.587, 51.0]) = 1
Diabetes([7.0, 100.0, 0.0, 0.0, 0.0, 30.0, 0.484, 32.0

In [ ]:
w

array([[0.48, 0.19, 0.69, ..., 0.48, 0.2 , 0.57],
       [0.4 , 0.87, 0.79, ..., 0.12, 0.75, 0.71],
       [3.48, 3.32, 3.61, ..., 3.47, 3.77, 0.13],
       ...,
       [0.24, 0.7 , 0.21, ..., 0.27, 0.38, 0.44],
       [3.91, 3.21, 3.07, ..., 3.76, 3.6 , 0.21],
       [0.41, 0.2 , 0.44, ..., 0.48, 0.41, 0.94]])

In [ ]:
b

-36.46000000000001

In [ ]:
errors

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., -1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [ ]:
for i in range(768):
    count = 0
    for j in range(8):
        if errors[i][j] == 0:
            count += 1
count

8

In [ ]:
count = 0
for i in range(len(input_)):
    if y_pred[i] == output[i]:
        count += 1
print((count/len(input_))*100)

100.0
