# Lab 2: Apply sigmoid neuron to solve a real-world classification / regression problem

In [1]:
from google.colab import files
uploaded = files.upload()

Saving stroke.csv to stroke.csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('stroke.csv')
data

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
def encode(Y):
  encoder = LabelEncoder()
  encoder.fit(Y)
  encoded_Y = encoder.transform(Y)
  dummy_Y = np_utils.to_categorical(encoded_Y)
  return dummy_Y

In [11]:
data['gender'] = encode(data['gender'])
data['ever_married'] = encode(data['ever_married'])
data['work_type'] = encode(data['work_type'])
data['Residence_type'] = encode(data['Residence_type'])
data['smoking_status'] = encode(data['smoking_status'])

In [12]:
data

id  gender   age  hypertension  heart_disease  ever_married  \
0      9046     0.0  67.0             0              1           1.0   
1     51676     1.0  61.0             0              0           1.0   
2     31112     0.0  80.0             0              1           1.0   
3     60182     1.0  49.0             0              0           1.0   
4      1665     1.0  79.0             1              0           1.0   
...     ...     ...   ...           ...            ...           ...   
5105  18234     1.0  80.0             1              0           1.0   
5106  44873     1.0  81.0             0              0           1.0   
5107  19723     1.0  35.0             0              0           1.0   
5108  37544     0.0  51.0             0              0           1.0   
5109  44679     1.0  44.0             0              0           1.0   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  \
0           0.0             0.0             228.69  36.6             0.0   
1           0.0             1.0             202.21   NaN             0.0   
2           0.0             1.0             105.92  32.5             0.0   
3           0.0             0.0             171.23  34.4             0.0   
4           0.0             1.0             174.12  24.0             0.0   
...         ...             ...                ...   ...             ...   
5105        0.0             0.0              83.75   NaN             0.0   
5106        0.0             0.0             125.20  40.0             0.0   
5107        0.0             1.0              82.99  30.6             0.0   
5108        0.0             1.0             166.29  25.6             0.0   
5109        1.0             0.0              85.28  26.2             1.0   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [14]:
data.dropna(inplace=True)

In [15]:
data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [19]:
data.drop('id',axis=1,inplace=True)

In [20]:
data

gender   age  hypertension  heart_disease  ever_married  work_type  \
0        0.0  67.0             0              1           1.0        0.0   
2        0.0  80.0             0              1           1.0        0.0   
3        1.0  49.0             0              0           1.0        0.0   
4        1.0  79.0             1              0           1.0        0.0   
5        0.0  81.0             0              0           1.0        0.0   
...      ...   ...           ...            ...           ...        ...   
5104     1.0  13.0             0              0           0.0        0.0   
5106     1.0  81.0             0              0           1.0        0.0   
5107     1.0  35.0             0              0           1.0        0.0   
5108     0.0  51.0             0              0           1.0        0.0   
5109     1.0  44.0             0              0           1.0        1.0   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                0.0             228.69  36.6             0.0       1  
2                1.0             105.92  32.5             0.0       1  
3                0.0             171.23  34.4             0.0       1  
4                1.0             174.12  24.0             0.0       1  
5                0.0             186.21  29.0             0.0       1  
...              ...                ...   ...             ...     ...  
5104             1.0             103.08  18.6             1.0       0  
5106             0.0             125.20  40.0             0.0       0  
5107             1.0              82.99  30.6             0.0       0  
5108             1.0             166.29  25.6             0.0       0  
5109             0.0              85.28  26.2             1.0       0  

[4909 rows x 11 columns]

In [22]:
a = data.iloc[:,:10]
input_ = a.values.tolist()
input_
input_

[[0.0, 67.0, 0.0, 1.0, 1.0, 0.0, 0.0, 228.69, 36.6, 0.0],
 [0.0, 80.0, 0.0, 1.0, 1.0, 0.0, 1.0, 105.92, 32.5, 0.0],
 [1.0, 49.0, 0.0, 0.0, 1.0, 0.0, 0.0, 171.23, 34.4, 0.0],
 [1.0, 79.0, 1.0, 0.0, 1.0, 0.0, 1.0, 174.12, 24.0, 0.0],
 [0.0, 81.0, 0.0, 0.0, 1.0, 0.0, 0.0, 186.21, 29.0, 0.0],
 [0.0, 74.0, 1.0, 1.0, 1.0, 0.0, 1.0, 70.09, 27.4, 0.0],
 [1.0, 69.0, 0.0, 0.0, 0.0, 0.0, 0.0, 94.39, 22.8, 0.0],
 [1.0, 78.0, 0.0, 0.0, 1.0, 0.0, 0.0, 58.57, 24.2, 1.0],
 [1.0, 81.0, 1.0, 0.0, 1.0, 0.0, 1.0, 80.43, 29.7, 0.0],
 [1.0, 61.0, 0.0, 1.0, 1.0, 1.0, 1.0, 120.46, 36.8, 0.0],
 [1.0, 54.0, 0.0, 0.0, 1.0, 0.0, 0.0, 104.51, 27.3, 0.0],
 [1.0, 79.0, 0.0, 1.0, 1.0, 0.0, 0.0, 214.09, 28.2, 0.0],
 [1.0, 50.0, 1.0, 0.0, 1.0, 0.0, 1.0, 167.41, 30.9, 0.0],
 [0.0, 64.0, 0.0, 1.0, 1.0, 0.0, 0.0, 191.61, 37.5, 0.0],
 [0.0, 75.0, 1.0, 0.0, 1.0, 0.0, 0.0, 221.29, 25.8, 0.0],
 [1.0, 60.0, 0.0, 0.0, 0.0, 0.0, 0.0, 89.22, 37.8, 0.0],
 [1.0, 71.0, 0.0, 0.0, 1.0, 1.0, 1.0, 193.94, 22.4, 0.0],
 [1.0, 52.0, 1.0, 0

In [23]:
output = data['stroke'].tolist()
output

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [43]:
import numpy as np
w = np.zeros((4909 ,10))
w

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
import random

In [44]:
for i in range(4909):
    for j in range(10):
        a = round(random.uniform(0, 1), 2)
        w[i][j] = a
w.astype(float)
w

array([[0.37, 0.77, 0.87, ..., 0.31, 0.56, 0.92],
       [0.7 , 0.11, 1.  , ..., 0.05, 0.21, 0.39],
       [0.28, 0.74, 0.74, ..., 0.72, 0.77, 0.01],
       ...,
       [0.47, 0.22, 0.25, ..., 0.53, 0.69, 0.23],
       [0.1 , 0.23, 0.59, ..., 0.79, 0.79, 0.77],
       [0.39, 0.05, 0.22, ..., 0.53, 0.96, 0.87]])

In [32]:
b = round(random.uniform(0, 1), 2)
b

0.53

In [33]:
def sigmoid_function(x):
    return 1/(1 + np.exp(-x))

In [34]:
def sigmoid_deriv(x):
    return x * (1 - x)

In [35]:
def error(out,i):
    return output[i] - out

In [45]:
errors = np.zeros((4909 ,10)).astype(float)
errors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
y_pred = []
for i in range(4909 ):
    sum = 0
    out = 0
    a = 0
    for j in range(10):
        sum += input_[i][j]*w[i][j] + b
    out = sigmoid_function(sum)
    a = -1*error(out,i)
    q = out*(1-out)
    p = input_[i][j]
    
    if a != 0:
        errors[i][j] = a
    while a != 0:
        for j in range(8):
            sum += input_[i][j]*w[i][j] + b
        out = sigmoid_function(sum)
        a = error(out,i)
        print("error = %.2f output = %.2f" %(a,out))
        if a != 0:
            errors[i][j] = a 
        for j in range(8):
            w[i][j] = w[i][j] + a*output[i]
        b = b + a
        print("updated_weight = %.2f updated_bias = %.2f" %(w[i][j],b))
    y_pred.append(out)
    print("Brain Stroke({}) = {}".format(input_[i],out))
    print()

error = 1.00 output = 0.00
updated_weight = 1.31 updated_bias = -36.79
error = 1.00 output = 0.00
updated_weight = 2.31 updated_bias = -35.79
error = 0.00 output = 1.00
updated_weight = 2.31 updated_bias = -35.79
Brain Stroke([0.0, 67.0, 0.0, 1.0, 1.0, 0.0, 0.0, 228.69, 36.6, 0.0]) = 1.0

error = 1.00 output = 0.00
updated_weight = 1.05 updated_bias = -34.79
error = 1.00 output = 0.00
updated_weight = 2.05 updated_bias = -33.79
error = 1.00 output = 0.00
updated_weight = 3.05 updated_bias = -32.79
error = 1.00 output = 0.00
updated_weight = 4.05 updated_bias = -31.79
error = 0.00 output = 1.00
updated_weight = 4.05 updated_bias = -31.79
Brain Stroke([0.0, 80.0, 0.0, 1.0, 1.0, 0.0, 1.0, 105.92, 32.5, 0.0]) = 1.0

error = 1.00 output = 0.00
updated_weight = 1.72 updated_bias = -30.79
error = 1.00 output = 0.00
updated_weight = 2.72 updated_bias = -29.79
error = 0.00 output = 1.00
updated_weight = 2.72 updated_bias = -29.79
Brain Stroke([1.0, 49.0, 0.0, 0.0, 1.0, 0.0, 0.0, 171.23, 34.4, 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


Streaming output truncated to the last 5000 lines.
Brain Stroke([1.0, 37.0, 0.0, 0.0, 0.0, 0.0, 1.0, 112.02, 29.1, 1.0]) = 0.0

error = -0.00 output = 0.00
updated_weight = 0.59 updated_bias = -38.08
error = -0.00 output = 0.00
updated_weight = 0.59 updated_bias = -38.08
error = -0.00 output = 0.00
updated_weight = 0.59 updated_bias = -38.08
error = -0.00 output = 0.00
updated_weight = 0.59 updated_bias = -38.08
error = 0.00 output = 0.00
updated_weight = 0.59 updated_bias = -38.08
Brain Stroke([1.0, 66.0, 0.0, 1.0, 1.0, 0.0, 1.0, 196.58, 41.9, 0.0]) = 0.0

error = -0.00 output = 0.00
updated_weight = 0.61 updated_bias = -38.08
error = 0.00 output = 0.00
updated_weight = 0.61 updated_bias = -38.08
Brain Stroke([1.0, 16.0, 0.0, 0.0, 0.0, 0.0, 0.0, 89.14, 22.6, 0.0]) = 0.0

error = -0.00 output = 0.00
updated_weight = 0.48 updated_bias = -38.08
error = 0.00 output = 0.00
updated_weight = 0.48 updated_bias = -38.08
Brain Stroke([1.0, 51.0, 1.0, 0.0, 1.0, 1.0, 0.0, 69.94, 33.3, 0.0]) = 0.0

In [47]:
w

array([[2.37, 2.77, 2.87, ..., 2.31, 0.56, 0.92],
       [4.7 , 4.11, 5.  , ..., 4.05, 0.21, 0.39],
       [2.28, 2.74, 2.74, ..., 2.72, 0.77, 0.01],
       ...,
       [0.47, 0.22, 0.25, ..., 0.53, 0.69, 0.23],
       [0.1 , 0.23, 0.59, ..., 0.79, 0.79, 0.77],
       [0.39, 0.05, 0.22, ..., 0.53, 0.96, 0.87]])

In [48]:
b

-38.080662573797426

In [49]:
errors

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         1.00000000e+000,  0.00000000e+000, -1.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         1.00000000e+000,  0.00000000e+000, -1.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         1.00000000e+000,  0.00000000e+000, -1.00000000e+000],
       ...,
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
        -5.47203879e-243,  0.00000000e+000,  8.23568649e-134],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
        -3.98979863e-304,  0.00000000e+000,  8.51694830e-095],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
        -1.45883236e-244,  0.00000000e+000,  1.56453965e-133]])

In [50]:
count = 0
for i in range(len(input_)):
    if y_pred[i] == output[i]:
        count += 1
print((count/len(input_))*100)

100.0
